---
name: pico
owner: vkottler
description: A firmware project for Raspberry Pi microcontrollers.
embedded: true

main_branch: master

# Caused by pico-sdk.
format: false

version:
  major: 0
  minor: 3
  patch: 1
