---
name: Yambs Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GITHUB_API_TOKEN: ${{secrets.API_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.12]

    env:
      PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@main
        with:
          python-version: ${{matrix.python-version}}
          cache: pip

      - run: pip${{matrix.python-version}} install vmklib>=1.8.0 yambs

      - run: mk dz-sync

      - run: mk yaml python-lint python-sa

      # - name: setup clang 18
      #   run: |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x ./llvm.sh
      #     sudo ./llvm.sh 18
      #     rm llvm.sh
      - run: sudo apt-get install doxygen
      - run: mk download-toolchains
      - run: mk g
      - run: ninja all
      - run: mk dist docs variant=pico
        if: github.ref_name != 'master'

      - run: mk release variant=pico
        if: |
          env.GITHUB_API_TOKEN != ''
          && github.ref_name == 'master'
